### ISSUE TITLE
Couldn't download - virus detected

### ISSUE THREAD

**Issue by Jab11n** [BirdOffice-Suite/birdpad#1]
First Edge told me it's not commonly downloaded and I had to click 3 different buttons to get around that, and then it wouldn't let me download it at all saying it's a virus.
![image](https://github.com/PPPDUD/birdpad/assets/118082374/e9e6ea49-cf0f-4803-bfd8-dbba1e7e4f43)

**Comment by Jab11n** [comment]
Microsoft really hates you doesn't it... I downloaded it thru Firefox to actually get it downloaded and Windows won't let me run it.
![image](https://github.com/PPPDUD/birdpad/assets/118082374/a3e29bf9-688a-42c6-889e-1c9c54d8d08c)

**Comment by Jab11n** [comment]
![image](https://github.com/PPPDUD/birdpad/assets/118082374/060b18e4-1534-45d0-8290-4338331e19d4)

**Comment by PPPDUD** [comment]
> ![image](https://private-user-images.githubusercontent.com/118082374/316191818-060b18e4-1534-45d0-8290-4338331e19d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDY3NDYsIm5iZiI6MTcxMTIwNjQ0NiwicGF0aCI6Ii8xMTgwODIzNzQvMzE2MTkxODE4LTA2MGIxOGU0LTE1MzQtNDVkMC04MjkwLTQzMzgzMzFlMTlkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNTA3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjljNjQzZTYzY2QyZjRjYjE5YzE0NDk5NDUzNDI5NTBjZGY2MjNhZjdkYmFmMmYzZTA5NWMzMGYwMGQ2MDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mDfESODzyGbLqrZD1g_n7i_-N5l06CSr0z0Fi-thmok)

Go to Actions and click Restore.

**Comment by Jab11n** [comment]
> Owner

what does this mean
also the image will not load, 
![image](https://github.com/PPPDUD/birdpad/assets/118082374/39f4df1a-96fe-4bf9-9f74-2931e6781c5a)

**Comment by PPPDUD** [comment]
What do you mean "owner"?

**Comment by Jab11n** [comment]
> What do you mean "owner"?

I don't know, I clicked quote reply and GitHub put that there instead of what you said for some reason.
